name: logger
description: Simple logging library for Flutter applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  talker_flutter: ^4.9.2
  talker_dio_logger: ^4.9.2
  talker_bloc_logger: ^4.9.2
  stack_trace: ^1.12.1
  clock: ^1.1.2
  meta: ^1.16.0
  intl: ^0.20.2

flutter:
  uses-material-design: true