name: product_catalog
description: "Product catalog domain module"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  dio: ^5.8.0+1
  drift: ^2.27.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  built_collection: ^5.1.1
  infinite_scroll_pagination: ^5.1.0
  common:
    path: ../../core/common
  logger:
    path: ../../core/logger
  database:
    path: ../../core/database
  rest_client:
    path: ../../core/rest_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.3
  freezed: ^3.0.6
  json_serializable: ^6.9.5